# Generated by Django 4.1.1 on 2022-10-15 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='usersrequests',
            options={'verbose_name': 'Users request', 'verbose_name_plural': 'Users requests'},
        ),
        migrations.RemoveField(
            model_name='users',
            name='time_update',
        ),
    ]
