# Generated by Django 4.1.1 on 2022-10-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_users_options_alter_usersrequests_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='telegram_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
