# Generated by Django 4.1.1 on 2022-10-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_users_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersrequests',
            name='image',
            field=models.FilePathField(),
        ),
    ]
