# Generated by Django 4.1.1 on 2022-10-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_usersrequests_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersrequests',
            name='image',
            field=models.FilePathField(path='D:/Courses spring/ML System Design/app/dashboard'),
        ),
    ]
