# Generated by Django 4.1.1 on 2022-10-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_usersrequests_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersrequests',
            name='image',
            field=models.ImageField(upload_to='media/photo'),
        ),
    ]
