# Generated by Django 4.1.1 on 2022-10-15 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_usersrequests_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersrequests',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.users'),
        ),
    ]
