# Generated by Django 4.1.1 on 2022-10-15 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_usersrequests_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersrequests',
            old_name='user_id',
            new_name='user',
        ),
    ]
